### ISSUE TITLE
get http request done to me.

### ISSUE THREAD

**Issue by Surt** [auraphp/Aura.Http#18]
Hi, I was reading the documentation and I still don't get how to get the actual request done to me. On a single example:

on an index.php file on the root.
Instantiate the manager.
How can I take the request done to me? I tried creating a new Request and Response but they are empty. 
What I want is to take the request sended to my index.php.

Thanks!

**Comment by harikt** [comment]
Hey @Surt ,

Have replied via email.

You are looking for Aura.Web . See https://github.com/auraphp/Aura.Web#the-context-object

The Aura.Http request is building http request, see eg: https://github.com/auraphp/Aura.Http#further-examples

**Comment by Surt** [comment]
Oh! thaks, will look into it then. :)

**Comment by harikt** [comment]
Also be patient, I noticed 3 places for the same query :) .
