### ISSUE TITLE
Remove dependency on curl 

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Http#19]
To send an http response we don't need curl, so it will be good to remove the dependency to be removed for `newResponse` object.

https://github.com/auraphp/Aura.Http/blob/develop/scripts/instance.php

**Comment by pmjones** [comment]
Strictly speaking, there's no dependency on curl. If it's available we use it; if not, we use something else. Am I maybe missing what you're getting at?

**Comment by harikt** [comment]
@pmjones what I was thinking was something like for an http response we don't need curl nor stream.

So may be remove that on the manager.

Only add it when people asks for new http client .

**Comment by pmjones** [comment]
Mmmm, I get you.  Even so, the Response object doesn't _use_ curl or stream. There's no dependency in the first place. I get that you want to remove it from the instance.php script, but I don't see the point.

**Comment by harikt** [comment]
see the comment by @stanlemon  asking  https://github.com/stanlemon/phalcon-v-symfony/pull/1#issuecomment-27276482

>  I was under the impression Aura/Http was basically a Curl wrapper, no?

**Comment by pmjones** [comment]
@harikt Do we still have a problem here? I confess I don't see what the trouble is.

**Comment by harikt** [comment]
@pmjones the only one trouble I am seeing now is if I just need to send I response I don't need streams or curl . That fix is for v2 ( and I like you to remember it ) . Other than that no.

**Comment by pmjones** [comment]
If you need to send a response to the client, no, you don't need curl.

But that's not the primary purpose of Aura.Http. Primarily, it is to send requests and receive responses, and secondarily to send a response to a client. The request portion does need curl (or streams) in order to do that. So we cannot remove the dependency on curl, even when we bring Aura.Http over to v2.

I hope that makes sense.

**Comment by harikt** [comment]
@pmjones I do understand.

To correct what I mean. Have a factory as in Aura.Web . My idea is to make something similar to the one done by Aura.Web  `$request = $factory->newRequest();` and `$response = $factory->newResponse();` now you can do request and get response. But I may be wrong here, when the response got back is same as the Response of the one that can send response to browser.

And I will look into the code for more information on the inner working.

Thank you

**Comment by stanlemon** [comment]
Hey guys, I vaguely recall the conversation w/ @harikt that I think might have spawned the writing of this issue.  IMO this boils down to a separation of concerns item. I may want to deal with response rendering, cookies, etc and have absolutely no desire to use the CURL wrapper.  In fact, truthfully, I probably would want to use Guzzle for such a thing. The conversation @harikt and I had (and please correct me if I'm wrong @harikt) had to do with my perception of Aura.Http mirroring the "purpose" of Symfony's HttpFoundation component.  Now the two may not be similar things, and that's fine - but I guess I would still suggest maybe questioning whether or not two purposes are being served here rather than just the one.  Just my $.02 and be forewarned it might not even be worth that much! ;)

**Comment by pmjones** [comment]
If anything, Aura.Http's intent mirrors Guzzle more than anything else: send requests, get back responses.

**Comment by stanlemon** [comment]
Your request part is, but the response part is a different beast altogether and has no relation to curl. Right?

**Comment by harikt** [comment]
> Primarily, it is to send requests and receive responses

But I do is with @stanlemon here, for using guzzle. It has some additional functionality . One thing I like in it is 

```
* Pluggable HTTP adapters that can send requests serially or in parallel
```

And as it is very well maintained, an over head of request and response that need to be maintained in Aura.Http is less. See bug https://github.com/auraphp/Aura.Http/issues/23 and the time we may take to fix it.

I love to reduce Aura.Http to just send response. And to make it work great with guzzle's response if we need to handle the response back.

**Comment by stanlemon** [comment]
+1 @harikt That's what I was trying to get at. :)

There are two meaning to 'request' and I think this is part of the confusion. I am accustomed to the response implementation as you have it being accompanied with an object that contains various HTTP headers, cookies and other pieces of data (like user agent).  That is a 'request', but your 'request' here is an external request not the executed contextual request.  Hopefully that helps clarify what we're getting at.

**Comment by pmjones** [comment]
There would be need to even _have_ Aura.Http v2  if all it does is "send a response". Aura.Web Response, and the web kernel, are enough for that. So removing the v1 dependency on curl is still out.

**Comment by pmjones** [comment]
@harikt I think you are missing the main point of this package. It is _not_ for the normal response from a controller action. It is for encapsulating the response received from a request made to another website, e.g. an API. It has the benefit of being able to be used as the response from a controller action, but that is not it's main purpose.

**Comment by harikt** [comment]
> So removing the v1 dependency on curl is still out.

not sure what you mean.

> I think you are missing the main point of this package

Probably.

And to what you were suggesting 

> e.g. an API. It has the benefit of being able to be used as the response from a controller action, but that is not it's main purpose.

What I am telling is have a wrapper of the Guzzle response.

``` php
$client = new GuzzleHttp\Client();
$response = $client->get('http://guzzlephp.org');
$res = $client->get('https://api.github.com/user', ['auth' =>  ['user', 'pass']]);
echo $res->getStatusCode();
```

The response you got from guzzle ( I guess this will be the new PSR ) to be compatible with the Aura.Http response object something like

``` php
// $http is Aura.Http object
$makeauraresponse = $http->setResponse($response);
// this will do set the response code, response body what all response guzzle gives back.
```

So the request part is completely handled by Guzzle. But I am not against you moving the functionality in Aura.Http . But I do prefer Guzzle is what I meant .
