### ISSUE TITLE
Incorrect status header for FCGI SAPIs

### ISSUE THREAD

**Issue by paulyg** [auraphp/Aura.Http#2]
Hi,

The following line https://github.com/auraphp/Aura.Http/blob/master/src/Response.php#L114 will cause the status header to not be set when using a FastCGI SAPI (IIS, Lighttpd, mod_fcgi). The status emitted by PHP will default back to 200 or 302 if you set a `Location` header. To emit the correct HTTP status you must set the header to `Status: $code $code_text`. See http://www.php.net/manual/en/function.header.php.

I use the following code:

``` php
    // catches 'cgi' (PHP < 5.3), 'cgi-fcgi' (PHP >= 5.3), & 'fpm-fcgi'
    if (strpos(php_sapi_name(), 'cgi') !== false) {
        header('Status:' . $code);
    } else {
        header('HTTP/1.1' . $code);
    }
```

**Comment by harikt** [comment]
@paulyg Galestic Void is experimenting with something . Also @pmjones seems busy . We will look into it and make the necessary changes.
Thanks

**Comment by pmjones** [comment]
At the time of the paulyg comment, the relevant code looked like this:

```
public function sendHeaders()
{
    if (headers_sent($file, $line)) {
        throw new Exception\HeadersSent($file, $line);
    }
    // build and send the status
    $status = "HTTP/{$this->version} {$this->status_code}";
    if ($this->status_text) {
        $status .= " {$this->status_text}";
    }
    header($status, true, $this->status_code);

    // send the non-cookie headers
    $this->headers->send();

    // send the cookie headers
    $this->cookies->send();
}
```

Line 114 was the `$status = "HTTP/{$this->version} {$this->status_code}";' bit.

**Comment by pmjones** [comment]
Fixed in https://github.com/auraphp/Aura.Http/commit/c8ba7a6adb4ce5085547878b9570c115d2ab565e. Thanks paulyg!
