### ISSUE TITLE
Http Client

### ISSUE THREAD

**Issue by harikt** [auraphp/Aura.Http#3]
Hi @pmjones  , 

@galactic-void branch has some additional features. I am not sure why he gave a pull request . Can you check with it and merge ?

https://github.com/galactic-void/Nursery/tree/master/aura.http/src

Those features are good to have ;) .

**Comment by pmjones** [comment]
There is a ton of stuff in there.  It seems like the OAuth pieces should be separated out to their own package.

**Comment by harikt** [comment]
What about the HttpClient ? I guess HttpClient needs to be incorporated . I strongly ll say :) .
Using Adapters like cURL , streams etc . What do you feel ?

**Comment by harikt** [comment]
What about including this in Beta3 ?

**Comment by pmjones** [comment]
harikt: i like that plan. galactic-void: how does that sound? do you feel like your http work is ready for inclusion?

**Comment by harikt** [comment]
@galactic-void ping ?

**Comment by harikt** [comment]
As its merged I am closing the issue .
