### ISSUE TITLE
Curlopt deprecated in php 5.5

### ISSUE THREAD

**Issue by jwoodcock** [auraphp/Aura.Http#31]
When trying to upload a file using the @filename syntax, or trying to upload a multipart file, the Http class broke pointing out that curlopt for sending files is deprecated and to use CurlFile class instead. 

Error: 
"file_get_contents(/Users/jwoodcock/code/Tandum.Api_Web/tests/api/src/testfile.jpg): failed to open stream: No such file or directory"

/Users/{user}/code/{repo}/vendor/aura/http/src/Multipart/FormData.php:195
/Users/{user}/code/{repo}/vendor/aura/http/src/Multipart/FormData.php:138
/Users/{user}/code/{repo}/vendor/aura/http/src/Adapter/StreamAdapter.php:373
/Users/{user}/code/{repo}/vendor/aura/http/src/Adapter/StreamAdapter.php:311
/Users/{user}/code/{repo}/vendor/aura/http/src/Adapter/StreamAdapter.php:238
/Users/{user}/code/{repo}/vendor/aura/http/src/Adapter/StreamAdapter.php:184
/Users/{user}/code/{repo}/vendor/aura/http/src/Transport/Transport.php:142
/Users/{user}/code/{repo}/vendor/aura/http/src/Http.php:110

System:
PHP 5.5.18
OSX

Also tested on:
PHP 5.6
Ubuntu

**Comment by harikt** [comment]
Hey @jwoodcock , 

Do you have any code which I can just copy and test ? Sorry being lazy and asking you.
If not I will look into this.  I am looking at a patch and probably something like that can be incorportated.

https://www.drupal.org/files/issues/2333345_imageapi_optimize_deprecated_curl_setopt_file.patch

**Comment by harikt** [comment]
I am really sorry that this wasn't addressed.

I did something today that can fix the issue https://github.com/auraphp/Aura.Http/pull/42 .

If there are better ideas it is welcome.

**Comment by harikt** [comment]
@jwoodcock this have been fixed in the 2.x branch. In case if you still have trouble feel free to re-open.

Thank you
