### ISSUE TITLE
StreamAdapter expects a prefixed http or https

### ISSUE THREAD

**Issue by jwoodcock** [auraphp/Aura.Http#32]
In aura/http/src//Adapter/StreamAdapter.php when setting context, setContext(), it does a url parse based on what the user inputed assumes a scheme has been provided. If this scheme is not there, it crashes. 

Found when config setting in app was using an IP with no scheme. IE: 192.168.1.68/path/to/endpoint

This is happening on line 317 of the above mentioned file. A simple fix should be adding an condition before the if with the following:

if (empty($url['scheme']) {
    $url['scheme'] = 'http';
}

**Comment by pmjones** [comment]
fixed in #33
